name: employee_attendance
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  intl: ^0.20.1
  sqflite: ^2.4.1
  path: ^1.9.0
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
